report = '''
# 📊 Daily Market Snapshot — S&P 500 & NASDAQ
## Friday, March 13, 2026

---

*Disclaimer: This is an AI-generated market summary for informational purposes only. Not financial advice.*

---

## 📈 Major Index Performance

| Index | Close | Daily Change | % Change |
|-------|-------|-------------|----------|
| **S&P 500** | **6,632.19** | -40.43 | **-0.61%** |
| **NASDAQ Composite** | **22,105.36** | -206.62 | **-0.93%** |
| **Dow Jones Industrial Avg** | **46,558.47** | -119.38 | **-0.26%** |
| **VIX (Fear Index)** | **27.21** | -0.08 | **-0.29%** |

---

## 🟢 Top 5 Gainers of the Day

| Ticker | Company Name | Close Price | % Change |
|--------|-------------|-------------|----------|
| SVCO | Silvaco Group | — | **+52.42%** |
| ELPW | Clean Earth Acquisitions | — | **+43.73%** |
| PLYX | PlayOLG (Playtika) | — | **+36.77%** |
| EDHL | Edgewell Personal Care | — | **+22.54%** |
| APEI | American Public Education | — | **+21.19%** |

---

## 🔴 Top 5 Losers of the Day

| Ticker | Company Name | Close Price | % Change |
|--------|-------------|-------------|----------|
| ULTA | Ulta Beauty, Inc. | $535.72 | **-14.24%** |
| MEOH | Methanex Corporation | $51.75 | **-10.87%** |
| CACC | Credit Acceptance Corp | $447.79 | **-9.35%** |
| EQX | Equinox Gold Corp. | $14.57 | **-8.48%** |
| AG | First Majestic Silver | $22.56 | **-8.40%** |

*Notable large-cap decliner: **Adobe (ADBE)** fell sharply, and gold/silver miners sold off heavily as gold dropped ~2%.*

---

## 🏭 Sector Performance (11 GICS Sectors)

| Rank | Sector | ETF | Daily % Change |
|------|--------|-----|----------------|
| 1 | **Utilities** | XLU | **+0.99%** 🟢 |
| 2 | **Consumer Staples** | XLP | **+0.58%** 🟢 |
| 3 | **Energy** | XLE | **+0.33%** 🟢 |
| 4 | **Real Estate** | XLRE | **+0.26%** 🟢 |
| 5 | **Financials** | XLF | **+0.12%** 🟢 |
| 6 | **Health Care** | XLV | **-0.25%** 🔴 |
| 7 | **Industrials** | XLI | **-0.36%** 🔴 |
| 8 | **Consumer Discretionary** | XLY | **-0.59%** 🔴 |
| 9 | **Communication Services** | XLC | **-0.71%** 🔴 |
| 10 | **Technology** | XLK | **-0.75%** 🔴 |
| 11 | **Materials** | XLB | **-0.99%** 🔴 |

*Defensive sectors (Utilities, Staples) led as investors rotated out of growth/tech amid geopolitical uncertainty.*

---

## 📊 Trading Volume

| Index Proxy | Today\'s Volume | 20-Day Avg Volume | Ratio |
|-------------|----------------|-------------------|-------|
| SPY (S&P 500) | 83.0M | 84.6M | 0.98x |
| QQQ (NASDAQ-100) | 62.0M | 73.1M | 0.85x |

*Volume was slightly below average, suggesting the selloff lacked full conviction despite headline risks.*

---

## 🌐 Key Market Data Points

| Metric | Value | Change |
|--------|-------|--------|
| Crude Oil (WTI) | $98.85/bbl | **+3.26%** |
| Gold | $5,023.90/oz | **-1.99%** |
| 10-Year Treasury Yield | 4.285% | +0.28% |
| Bitcoin | $71,436.28 | +0.37% |

---

## 📰 Notable Market Events

1. **🛢️ Iran Oil Crisis Escalates** — Iranian tanker attacks and Trump\'s threat to strike Iran "very hard" sent crude oil surging above $98/bbl (+3.3%), reigniting inflation fears and stagflation concerns.

2. **📉 GDP Downgrade** — US Q4 GDP was revised sharply lower to just **0.7% growth**, fueling recession/stagflation narrative alongside rising oil prices.

3. **🏛️ Fed on Sidelines** — PCE Price Index came in at 2.8% YoY (vs 2.9% prior), slightly encouraging, but the Fed is expected to remain on hold given geopolitical uncertainty and sticky inflation from energy.

4. **⚖️ Fed Legal Victory** — A judge threw out subpoenas in a criminal probe, seen as a victory for Fed Chair Powell and institutional independence.

5. **📊 University of Michigan Sentiment** — Consumer sentiment data released, reflecting growing unease about inflation and geopolitical risks.

6. **💄 ULTA Crashes -14%** — Ulta Beauty plunged on disappointing earnings/guidance, the day\'s biggest large-cap loser.

7. **⛏️ Gold Miners Hammered** — Despite geopolitical tensions, gold fell ~2% and gold/silver miners (EQX, AG, GFI, AU, SBSW) dropped 7-8%.

---

## 📝 Market Summary

Stocks closed lower on Friday, March 13, 2026, extending the S&P 500\'s losing streak to three consecutive weeks — the longest since late 2024. The S&P 500 fell 0.61% to 6,632.19, the NASDAQ dropped 0.93% to 22,105.36, and the Dow shed 0.26% to 46,558.47, as escalating US-Iran tensions sent crude oil surging above $98/barrel and reignited stagflation fears. Defensive sectors like Utilities (+0.99%) and Consumer Staples (+0.58%) outperformed while Technology (-0.75%) and Materials (-0.99%) lagged, reflecting a classic risk-off rotation. The VIX remained elevated at 27.21, and with Q4 GDP revised down to just 0.7%, investors face a challenging macro backdrop heading into next week.

---

*Report generated by Sentinel AI Market Analyst | Data sources: Yahoo Finance, WSJ, yfinance*
'''

print(report)
