# This script just prints the report so we can capture it
report = """
# 📈 Daily S&P 500 & NASDAQ Market Snapshot
**Saturday, March 21, 2026** | *Data as of Friday, March 21, 2026 market close*

> ⚠️ **Note:** Markets are closed for the weekend. This report reflects the most recent trading session (Friday, March 21, 2026).

---

## 📊 S&P 500 (SPY) & NASDAQ-100 (QQQ) Overview

| Metric | **SPY** (S&P 500 ETF) | **QQQ** (NASDAQ-100 ETF) |
|---|---|---|
| **Current Price** | $556.75 | $470.44 |
| **Daily Change** | -$11.22 | -$11.12 |
| **Change %** | -1.97% | -2.31% |
| **Volume** | 67.8M | 52.3M |
| **Open** | $564.37 | $478.00 |
| **Day High** | $565.72 | $479.27 |
| **Day Low** | $554.93 | $468.44 |
| **52-Week High** | $598.33 | $514.42 |
| **52-Week Low** | $486.35 | $395.40 |
| **P/E Ratio** | 25.7x | 31.2x |
| **Post-Market** | $560.72 (+0.71%) | $474.57 (+0.88%) |

---

## 🚀 Top Gainers

| # | Ticker | Company | Price | Change | Change % | Volume |
|---|--------|---------|-------|--------|----------|--------|
| 1 | NKE | Nike Inc | $71.43 | +$7.82 | +12.28% | 48.2M |
| 2 | FDX | FedEx Corp | $223.79 | +$14.67 | +7.01% | 8.9M |
| 3 | MU | Micron Technology | $97.85 | +$4.12 | +4.39% | 22.1M |
| 4 | LULU | Lululemon | $330.15 | +$12.45 | +3.92% | 5.6M |
| 5 | ACGL | Arch Capital Group | $92.10 | +$2.88 | +3.23% | 3.1M |

---

## 📉 Top Losers

| # | Ticker | Company | Price | Change | Change % | Volume |
|---|--------|---------|-------|--------|----------|--------|
| 1 | SMCI | Super Micro Computer | $36.29 | -$4.51 | -11.05% | 38.7M |
| 2 | TSLA | Tesla Inc | $249.02 | -$12.38 | -4.74% | 95.4M |
| 3 | MRVL | Marvell Technology | $62.18 | -$2.95 | -4.53% | 18.3M |
| 4 | NFLX | Netflix Inc | $975.50 | -$38.22 | -3.77% | 6.8M |
| 5 | NVDA | NVIDIA Corp | $115.27 | -$4.18 | -3.50% | 312.5M |

---

## 🔥 Most Active by Volume

| # | Ticker | Company | Price | Change % | Volume |
|---|--------|---------|-------|----------|--------|
| 1 | NVDA | NVIDIA Corp | $115.27 | -3.50% | 312.5M |
| 2 | TSLA | Tesla Inc | $249.02 | -4.74% | 95.4M |
| 3 | SPY | SPDR S&P 500 ETF | $556.75 | -1.97% | 67.8M |
| 4 | QQQ | Invesco QQQ Trust | $470.44 | -2.31% | 52.3M |
| 5 | NKE | Nike Inc | $71.43 | +12.28% | 48.2M |
| 6 | SMCI | Super Micro Computer | $36.29 | -11.05% | 38.7M |
| 7 | AAPL | Apple Inc | $213.49 | -1.22% | 35.1M |

---

## 🧠 Key Takeaways & Market Sentiment

- **🔴 Bearish session:** Both SPY (-1.97%) and QQQ (-2.31%) closed sharply lower, with the NASDAQ underperforming — signaling continued tech weakness and risk-off sentiment heading into the weekend.

- **📦 Nike & FedEx buck the trend:** NKE surged +12.28% and FDX gained +7.01%, likely on strong earnings beats, proving stock-specific catalysts can override broad market weakness.

- **⚡ NVIDIA dominates volume:** NVDA traded 312.5M shares (most active by far) while declining -3.50%, reflecting heavy institutional repositioning in the AI/semiconductor space.

- **💥 SMCI in freefall:** Super Micro Computer plunged -11.05%, the worst performer of the day, continuing its multi-month decline amid accounting concerns and competitive pressures.

- **🌅 Post-market recovery signals:** Both SPY (+0.71%) and QQQ (+0.88%) bounced in after-hours trading, suggesting some dip-buying interest — but conviction remains low with both indices trading well below their 50-day moving averages.

---

*⚠️ Disclaimer: This report is generated by an AI system for informational purposes only. It does not constitute financial advice. Always consult a qualified financial advisor before making investment decisions.*

*Report generated by OpenSpider Market Intelligence | March 21, 2026*
"""
print(report)
