import subprocess
import json

message = """🔥 *X Trending Topics — Live Snapshot*
📅 Monday, March 30, 2026 | 2:45 AM PT

*1. Iran-US War Escalation / #IranWar*
📌 Category: Politics / Geopolitics
🔍 Trump reportedly considering seizing Iran's Kharg Island and 'taking the oil.' Pentagon preparing ground operations as conflict enters 5th week. Tehran targeting water/power facilities in Kuwait.
📊 ~500K+ tweets
📡 Sources: CNBC, Reuters, Google News, Reddit r/news, X Trending

*2. Oil Price Surge / $OIL / Brent Crude*
📌 Category: Stock Market / Energy
🔍 Brent crude heading for record monthly surge as Iran war escalates. Oil above $101/barrel. Budget airlines facing painful fuel cost reality. Energy stocks (HAL, APA) surging.
📊 ~300K+ tweets
📡 Sources: CNBC, Reuters, Reddit, Bloomberg

*3. Duke vs UConn / #FinalFour / #MarchMadness*
📌 Category: General / Sports
🔍 Duke and UConn clash in the NCAA Final Four. Coach Scheyer, Grant Hill, and Boozer trending. Massive engagement across sports Twitter.
📊 ~400K+ tweets
📡 Sources: X Trending #1, ESPN, Reddit r/CollegeBasketball

*4. 'No Kings' Protests / #NoKings*
📌 Category: Politics
🔍 Nationwide protests continue across the US under the 'No Kings' banner. Demonstrations gaining momentum with significant social media engagement and news coverage.
📊 ~250K+ tweets
📡 Sources: CNBC, Google News, X Trending, Reddit

*5. Houthi Attacks on Israel / Yemen Conflict*
📌 Category: Politics / Geopolitics
🔍 Yemeni Houthis launched attacks on Israel, widening the Iran conflict. Oil prices jumped on the news. Regional escalation fears intensifying.
📊 ~200K+ tweets
📡 Sources: Reuters, Reddit r/news, Google News, BBC

*6. Russia-Cuba Oil Tanker / Cuba Blockade*
📌 Category: Politics / Energy
🔍 Trump softened approach to US blockade, allowing Russian oil tanker to reach Cuba. Tanker reportedly arrived. Signals shift in US-Cuba-Russia dynamics.
📊 ~150K+ tweets
📡 Sources: Reuters, CNBC, Reddit r/news, NYT

*7. SCOTUS Birthright Citizenship Case*
📌 Category: Politics
🔍 Supreme Court hearing major case on birthright citizenship. Constitutional debate intensifying with significant political implications for immigration policy.
📊 ~180K+ tweets
📡 Sources: Google News, X Trending, AP News, Reddit

*8. Knicks / NBA Sunday*
📌 Category: General / Sports
🔍 Knicks trending after Sunday night game. Porzingis, Brunson, and Lu Dort generating buzz. NBA playoff positioning heating up.
📊 ~200K+ tweets
📡 Sources: X Trending, ESPN, Reddit r/nba

*9. Walmart Digital Price Labels*
📌 Category: Tech / Business
🔍 Walmart announcing digital price labels coming to every US store shelf by end of 2026. Sparking debate about dynamic pricing and consumer impact.
📊 ~120K+ tweets
📡 Sources: CNBC, Reddit r/news, X, Business Insider

*10. Mistral AI $830M Funding*
📌 Category: Tech / AI
🔍 French AI startup Mistral secures $830M in debt financing to fund AI data centers. Signals continued massive investment in AI infrastructure globally.
📊 ~80K+ tweets
📡 Sources: CNBC, TechCrunch, X, Reddit r/technology

---
⚡ _Report generated by OpenSpider Intelligence Agent_
🕐 _Next update in 6 hours_"""

print("Message prepared, length:", len(message))
print(message[:200])
