const { sendWhatsApp } = require('./tools/whatsapp');

const msg = `TOP 10 TRENDING TOPICS - March 28, 2026 (10:37 AM PDT)

1. US-IRAN WAR ESCALATION
Category: Politics/Military
US & Israel bombed Iran nuclear & steel facilities. Iran retaliated across Persian Gulf hitting Emirates Global Aluminium (significant damage). Gulf countries growing frustrated with US. Displaced families in Lebanon.
Approx Tweet Volume: ~500K+
Sources: Bloomberg, Reuters, BBC, Reddit

2. US STOCKS CRATER / NASDAQ CORRECTION
Category: Stock Market
Nasdaq 100 fell into correction (>10% from record). Wall Street longest weekly slide since 2022 driven by Iran war & oil fears.
Approx Tweet Volume: ~200K+
Sources: Bloomberg, CNBC, Reddit r/stocks

3. GOVERNMENT SHUTDOWN / TSA UNPAID
Category: Politics
House Republicans rejected Senate deal prolonging partial govt shutdown. Trump signed executive order to pay TSA employees. Travel chaos at airports.
Approx Tweet Volume: ~300K+
Sources: BBC, CNBC, Google News

4. TIGER WOODS DUI ARREST
Category: General/Sports
Tiger Woods arrested for DUI after rollover car crash in Florida. Major viral story across all platforms.
Approx Tweet Volume: ~400K+
Sources: CNBC, Reddit r/news, X trending

5. OIL PRICES / STRAIT OF HORMUZ INFLATION
Category: Stock Market/Economy
Oil prices elevated across all Iran war scenarios. Strait of Hormuz disruption causing plastics & petrochemical inflation. Consumer fuel prices rising.
Approx Tweet Volume: ~150K+
Sources: Bloomberg, CNBC, Reddit (130+ comments)

6. ELON MUSK LOSES TWITTER FRAUD TRIAL
Category: Tech/Legal
Musk lost shareholder fraud trial over Twitter acquisition. Took swipe at judge. Polymarket betting on his tweet counts hit $3.3M volume.
Approx Tweet Volume: ~250K+
Sources: X trending, Google News

7. IRAN HACKERS BREACH FBI DIRECTOR EMAIL
Category: Tech/Cybersecurity
Iran-linked hackers breached FBI Director Kash Patel's email account. Major cybersecurity incident amid ongoing war.
Approx Tweet Volume: ~100K+
Sources: Reuters, Google News

8. BANK OF AMERICA EPSTEIN SETTLEMENT
Category: General/Finance
Bank of America reached settlement in Epstein-related lawsuit. Story broke just 2 hours ago.
Approx Tweet Volume: ~80K+
Sources: BBC, Bloomberg

9. APPLE AI / SIRI OVERHAUL
Category: Technology
Apple hired ex-Google exec Lilian Rincon for AI/Siri marketing. Bloomberg Gurman Q&A on Apple's critical 2026 plans.
Approx Tweet Volume: ~120K+
Sources: Reuters, Bloomberg

10. US DOLLAR SURGE
Category: Stock Market/Economy
Dollar on track for best month since July 2024. Confounding Wall Street FX forecasters. Adding inflation risk.
Approx Tweet Volume: ~60K+
Sources: Bloomberg (2 articles)

Generated by OpenSpider Social Intel Agent`;

async function main() {
  try {
    const r1 = await sendWhatsApp('14156249639@s.whatsapp.net', msg);
    console.log('WA1:', JSON.stringify(r1));
  } catch(e) {
    console.error('WA1 error:', e.message);
  }
  try {
    const r2 = await sendWhatsApp('16507965072@s.whatsapp.net', msg);
    console.log('WA2:', JSON.stringify(r2));
  } catch(e) {
    console.error('WA2 error:', e.message);
  }
}
main();
