import os
os.makedirs('workspace/memory', exist_ok=True)
with open('workspace/memory/trump_truth_last_check.md', 'w') as f:
    f.write('# Trump Truth Social - Last Check\n\n')
    f.write('## Last Check Time\n')
    f.write('2026-03-21T18:47:00-07:00 (6:47 PM PDT, March 21, 2026)\n\n')
    f.write('## Posts Seen\n\n')
    f.write('### Post 1\n')
    f.write('- **Topic:** Robert Mueller Death Reaction\n')
    f.write('- **Approx Time:** ~4:25 PM PDT, March 21, 2026\n')
    f.write('- **Hash:** mueller_death_reaction_20260321\n\n')
    f.write('### Post 2\n')
    f.write('- **Topic:** Iran Military Escalation\n')
    f.write('- **Approx Time:** ~4:30 PM PDT, March 21, 2026\n')
    f.write('- **Hash:** iran_military_escalation_20260321\n\n')
    f.write('### Post 3\n')
    f.write('- **Topic:** 48-Hour Ultimatum to Iran Over Strait of Hormuz\n')
    f.write('- **Approx Time:** ~5:30 PM PDT, March 21, 2026\n')
    f.write('- **Hash:** iran_strait_hormuz_ultimatum_20260321\n')
print('File written successfully')